export default {
  PRODUCTS: [
    {
      id: "1",
      name: "Spoon",
      categoryId: "1",
      price: "22.45",
      quantity: "5",
      onSale: true,
      imageUrl: "https://via.placeholder.com/150/92c952",
      description: "accusamus beatae ad facilis cum similique qui sunt",
    },
    {
      id: "4",
      name: "Fork",
      categoryId: "1",
      price: "22.45",
      quantity: "5",
      onSale: false,
      imageUrl: "https://via.placeholder.com/150/92c952",
      description: "accusamus beatae ad facilis cum similique qui sunt",
    },
    {
      id: "2",
      name: "Shovel",
      categoryId: "2",
      price: "22.45",
      quantity: "5",
      onSale: true,
      imageUrl: "https://via.placeholder.com/150/771796",
      description: "reprehenderit est deserunt velit ipsam",
    },
    {
      id: "3",
      name: "Soccer Ball",
      categoryId: "3",
      price: "22.45",
      quantity: "5",
      onSale: false,
      imageUrl: "https://via.placeholder.com/150/24f355",
      description: "officia porro iure quia iusto qui ipsa ut modi",
    },
  ],
  CATEGORIES: [
    {
      id: "1",
      name: "Kitchen",
    },
    {
      id: "2",
      name: "Garden",
    },
    {
      id: "3",
      name: "Sports",
    },
  ],
  REVIEWS: [
    {
      id: "3",
      date: "2021-01-01",
      title: "This is bad",
      comment: "filthy",
      rating: 1,
      productId: "1",
    },
    {
      id: "1",
      date: "2021-04-23",
      title: "This is good",
      comment: "digs good",
      rating: 3,
      productId: "2",
    },
    {
      id: "2",
      date: "2020-04-23",
      title: "is okay",
      comment: "yes it is good i guess",
      rating: 2,
      productId: "3",
    },
  ],
};
